### ISSUE TITLE
footer references hr.png which is not in the images folder

### ISSUE THREAD

**Issue by roryprimrose** [jasonlong/architect-theme#12]

**Comment by jonorossi** [comment]
See #2 and #3.

**Comment by roryprimrose** [comment]
My bad, I only reviewed open issues. Thanks :)

**Comment by roryprimrose** [comment]
This file is still referenced in the style for footer, line 750

**Comment by jonorossi** [comment]
@roryprimrose ah, my bad I thought it was all fixed in #3.

**Comment by jasonlong** [comment]
Thanks @jonorossi. I've removed the `footer` style complete since this theme doesn't use that element. It looks like I copy/pasted this from my other theme.

**Comment by jonorossi** [comment]
@jasonlong interesting, I must have looked at the CSS or just guessed when I did http://www.castleproject.org/, because I've got a footer on it. I don't mind the change, I'll probably never update it directly because there are heaps of customisations already.

https://github.com/castleproject/castleproject.github.io/blob/master/_layouts/default.html#L95

**Comment by jasonlong** [comment]
Ah right on. I might revisit this later and move some of the sidebar content down to a real footer.
